steps:
  - name: "Docker Build"
    plugins:
      docker#v1.1.1:
        image: plugins/docker
        environment:
          - PLUGIN_REPO=justinbarrick/drone-terraform
          - PLUGIN_TAGS=latest       
