steps:
  - name: "Docker Build"
    plugins:
      docker-compose#v2.1.0:
        run: docker
        config: .buildkite/docker-compose.yml
        env:
          - BUILDKITE_BRANCH
          - BUILDKITE_COMMIT
          - PLUGIN_REPO=justinbarrick/drone-terraform
          - PLUGIN_TAGS=latest       
